version: 0.2
phases:
  install:
    commands:
#      - export GRADLE_USER_HOME=`pwd`/.gradle
#      - apt-get update --quiet --yes
#      - apt-get --quiet install --yes wget unzip
#      - wget --quiet --output-document=gradle.zip https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
#      - unzip -u -q gradle.zip
#      - ./gradlew clean shadowJar
      - aws cloudformation package --template-file samTemplate.yaml --kms-key-id 9ca66003-2df1-4afd-9464-bf5a44ffef13 --s3-bucket codepipeline-us-east-1-496872723175
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
