AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal serverless application for testing deployment, Returns "Hello World"
Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloHandler
      Runtime: java8
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
